// This file is automatically generated from your CSS. Any edits will be overwritten.
export const header: string;
export const active: string;
export const icon: string;
export const drawer: string;
