// This file is automatically generated from your CSS. Any edits will be overwritten.
export const changePassword: string;
export const full: string;
export const textRight: string;
export const error: string;
