// This file is automatically generated from your CSS. Any edits will be overwritten.
export const home: string;
export const card: string;
export const cardHeader: string;
export const cardBody: string;
export const contentEnd: string;
export const icon: string;
